version = 0.1
[default.deploy.parameters]
s3_bucket = "my-sam-deployment-bucket5"  # specify your custom bucket
resolve_s3 = true
stack_name = "sam-app"

s3_prefix = "sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
